QSA-75 Modified labels
Queueing-Systems-Assistance/qsa-feature-config-pack pull request #19
Opened 2020-11-19 21:10 UTC by kcsanad98

I consulted with Sztrik János and made the following changes:
- checked the label of all system features
- simplified labels where it was possible
- fixed typos
- corrected some symbols that didn't match the description

2020-11-19 21:56 UTC, ZoltanSzilagyiCse requested changes

2020-11-19 21:56 UTC, ZoltanSzilagyiCse commented on src/main/resources/config/FEATURES_ORDER.json
> +      "value": "Alpha,Beta,Ro,Ro1,Ro2,Lambda,Lambda1,Lambda2,LambdaN,LambdaAvg,Mu,Mua,Mub,mu1,mu2,mu3,bN,SAvg,SAvg1,SAvg2,SAvg3,NAvg,NAvg1,NAvg2,QAvg,QAvg1,QAvg2,WAvg,WAvg0,WAvg1,WAvg2,WAvgW,TAvg,TAv
I think there are a few extra values that should be removed (according to the deleted files):
- C1
- C2
- ETSt
- EWSt
- FW0
- FWW0
- SAvg1
- SAvg2
- SAvg3
- eS1
- eS12
- eS13
- eS2
- eS22
- eS23
- eS3
- eS32
- eS33

2020-11-20 13:13 UTC, kcsanad98 commented on src/main/resources/config/FEATURES_ORDER.json
> +      "value": "Alpha,Beta,Ro,Ro1,Ro2,Lambda,Lambda1,Lambda2,LambdaN,LambdaAvg,Mu,Mua,Mub,mu1,mu2,mu3,bN,SAvg,SAvg1,SAvg2,SAvg3,NAvg,NAvg1,NAvg2,QAvg,QAvg1,QAvg2,WAvg,WAvg0,WAvg1,WAvg2,WAvgW,TAvg,TAv
Huge thanks for collecting them!

2020-11-20 18:11 UTC, ZoltanSzilagyiCse requested changes
The FWWW0 is still present. Please remove it.

2020-11-20 18:35 UTC, ZoltanSzilagyiCse approved these changes

2020-11-20 18:47 UTC, merged